# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  webapp:
    image: webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5230:5230
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
