
version: '3.4'

services:
  webapp:
    image: webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
