name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # 'main' branch'e push yapıldığında çalışacak

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Kodu çekiyoruz

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub kullanıcı adınız (secrets'e ekleyin)
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub şifreniz (secrets'e ekleyin)

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: GithubAction/Dockerfile
        push: true
        tags: akamci/postgre:latest

    - name: Deploy Docker container
      run: |
        docker stop testOne || true
        docker rm testOne || true
        docker run -d --name testOne -p 8080:8080 akamci/postgre:latest
